name: "Install"
description: "Sets up Node.js and runs install"

runs:
  using: composite

  steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Check versions
      run: |
        echo "Node:" `node --version`
        echo "NPM:" `npm --version`
