name: "Install"
description: "Sets up Node.js and runs install"

runs:
  using: composite

  steps:
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      shell: bash
      run: npm install
